// <auto-generated />
namespace Books.Web.DataContexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DefaultSchema1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DefaultSchema1));
        
        string IMigrationMetadata.Id
        {
            get { return "201905121501304_DefaultSchema1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
